## numpy array란?

In [1]:
import numpy

In [2]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(11,)

In [6]:
array2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
type(array2)

numpy.ndarray

In [8]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
array2.shape

(3, 4)

In [10]:
array1.size

11

In [11]:
array2.size

12

---
## numpy array를 만드는 다양한 방법

In [12]:
array3 = numpy.full(6, 7)

In [13]:
array3

array([7, 7, 7, 7, 7, 7])

In [14]:
array4 = numpy.full(6, 0)
array5 = numpy.zeros(6, dtype=int)

print(array4)
print()
print(array5)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


In [15]:
array6 = numpy.full(6, 1)
array7 = numpy.ones(6, dtype=int)

print(array6)
print()
print(array7)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


In [16]:
array8 = numpy.random.random(6)
array9 = numpy.random.random(6)

print(array8)
print()
print(array9)

[0.51643401 0.83049071 0.48238733 0.09919897 0.07503445 0.24163993]

[0.84573743 0.24867217 0.33293018 0.26593484 0.51188117 0.83527055]


In [17]:
array10 = numpy.arange(6)
print(array10)

[0 1 2 3 4 5]


In [18]:
array11 = numpy.arange(2, 7)
print(array11)

[2 3 4 5 6]


In [19]:
array12 = numpy.arange(3, 17, 3)
print(array12)

[ 3  6  9 12 15]


---
## 모듈 별명 지어주기

In [20]:
import numpy as np

array1 = np.full(6, 0)
array2 = np.zeros(6)
array3 = np.full(6, 6)
array4 = np.ones(9)
array5 = np.random.random(6)
array6 = np.random.random(10)

In [21]:
import matplotlib.pyplot as plt

---
## numpy array 생성 연습1

In [22]:
arr = np.arange(1,101)

arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

---
## numpy array 생성 연습2

In [23]:
arr = np.arange(3,101,3)

arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

---
## 인덱싱, 슬라이싱

In [24]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [25]:
array1[0]

2

In [26]:
array1[2]

5

In [27]:
array1[-1]

31

In [28]:
array1[-2]

29

In [29]:
array1[[1, 3, 4]]  # 1번, 3번, 4번 인덱스의 값만 나타남

array([ 3,  7, 11])

In [30]:
array2 = np.array([2, 1, 3])

In [31]:
array1[array2]

array([5, 3, 7])

In [32]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [33]:
array1[0:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [34]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [35]:
array1[2:]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [36]:
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

In [37]:
array1[2:11:3]

array([ 5, 13, 23])

---
## numpy 기본 연산

In [38]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [39]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [43]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
array1 = array1 * 2

In [46]:
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
array1 = np.arange(10)

In [48]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [49]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [50]:
array1 / array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

---
## 신주쿠 흥부부대찌개

In [58]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

won_array = np.array(revenue_in_yen) * 10.08

won_array

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

---
## 흥부부대찌개 LA 진출

In [60]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

# 코드를 작성하세요.
yen_array = np.array(revenue_in_yen)
dollar_array = np.array(revenue_in_dollar)

won_array = yen_array * 10.08 + dollar_array * 1138

# 정답 출력
won_array

array([4389600., 5248000., 4818800., 5108200., 6825000., 3004400.,
       3521400., 5817000., 5033400., 4630200., 5439800., 6220200.,
       4900000., 4370000., 4253000., 5524400., 6421800., 6145400.,
       5651200., 3560400., 3612400., 5150400., 6220200., 7016800.,
       5589400., 6623400., 3560400., 3814000., 6018600., 5046400.,
       4568400.])

---
## numpy 불린 연산

In [61]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [62]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [63]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [64]:
booleans = np.array([True, True, False, True, True, False, True, True, True, False, True])

In [65]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [66]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [67]:
np.where(array1 > 4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [68]:
filter = np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [69]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

---
## 흥부부대찌개 목표 일 매출

In [70]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.
array_yen = np.array(revenue_in_yen)
filter = np.where(array_yen <= 200000)
bad_days_revenue = array_yen[filter]

# 정답 출력
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

---
## numpy 기본 통계

In [71]:
import numpy as np

array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.max()) # 최댓값
print(array1.min()) # 최솟값

31
5


In [72]:
print(array1.mean()) # 평균값

15.25


In [73]:
array1 = np.array([8, 12, 9, 15, 16])
array2 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(np.median(array1)) # 중앙값
print(np.median(array2)) # 중앙값

12.0
13.5


In [74]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.std()) # 표준 편차
print(array1.var()) # 분산

8.496322733983215
72.1875
